----------------------------------------------------------------------------------------------------------------------
DROP USER CIPRI;
CREATE USER CIPRI IDENTIFIED BY password;
GRANT CREATE SESSION, CREATE TABLE, CREATE TRIGGER, CREATE SEQUENCE TO CIPRI;
ALTER USER CIPRI QUOTA UNLIMITED ON USERS;
----------------------------------------------------------------------------------------------------------------------
DROP TABLE PERCENTAGES;

CREATE TABLE PERCENTAGES(
    DEFAULT_PERCENTAGE_TAX_PENSION INT DEFAULT ON NULL 25,
    DEFAULT_PERCENTAGE_TAX_HEALTH INT DEFAULT ON NULL 10,
    DEFAULT_PERCENTAGE_TAX_INCOME INT DEFAULT ON NULL 10,
    DEFAULT_PERCENTAGE_GROSS_INCREASE INT DEFAULT ON NULL 0,
    DEFAULT_VALUE_DEDUCTIONS INT DEFAULT ON NULL 0,
    DEFAULT_VALUE_GROSS_PRIZES INT DEFAULT ON NULL 0,
    ENCRYPTED_TABLE_PASSWORD VARCHAR(128)
);

INSERT INTO PERCENTAGES(ENCRYPTED_TABLE_PASSWORD)
VALUES('5F-4D-CC-3B-5A-A7-65-D6-1D-83-27-DE-B8-82-CF-99');

SELECT * FROM PERCENTAGES;
----------------------------------------------------------------------------------------------------------------------
DROP TABLE EMPLOYEES;

CREATE TABLE EMPLOYEES(
ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
SURNAME VARCHAR(30) NOT NULL,
FIRST_NAME VARCHAR(30) NOT NULL,
OCCUPATION VARCHAR(30) NOT NULL,
GROSS_SALARY INT NOT NULL,
GROSS_INCREASE INT,
GROSS_PRIZES INT,
GROSS_TOTAL INT,
GROSS_TAXABLE INT,
TAX_INCOME INT,
TAX_PENSION INT,
TAX_HEALTH INT,
DEDUCTIONS INT,
NET_SALARY INT,
CONSTRAINT EMPLOYEES_PK PRIMARY KEY(ID)
);

CREATE OR REPLACE TRIGGER COMPUTE_SALARY_NEW_EMPLOYEE
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
    TAX_PENSION_PERCENTAGE INT;
    TAX_HEALTH_PERCENTAGE INT;
    TAX_INCOME_PERCENTAGE INT;
    GROSS_INCREASE INT;
    DEDUCTIONS INT;
    GROSS_PRIZES INT;
BEGIN
    SELECT DEFAULT_PERCENTAGE_TAX_PENSION, DEFAULT_PERCENTAGE_TAX_HEALTH, DEFAULT_PERCENTAGE_TAX_INCOME,
    DEFAULT_PERCENTAGE_GROSS_INCREASE, DEFAULT_VALUE_DEDUCTIONS, DEFAULT_VALUE_GROSS_PRIZES
    INTO TAX_PENSION_PERCENTAGE, TAX_HEALTH_PERCENTAGE, TAX_INCOME_PERCENTAGE,
    GROSS_INCREASE, DEDUCTIONS, GROSS_PRIZES
    FROM PERCENTAGES;

    :NEW.GROSS_INCREASE := GROSS_INCREASE;
    :NEW.GROSS_PRIZES := GROSS_PRIZES;
    :NEW.DEDUCTIONS := DEDUCTIONS;

    :NEW.GROSS_TOTAL := :NEW.GROSS_SALARY * (1 + :NEW.GROSS_INCREASE / 100) + :NEW.GROSS_PRIZES;
    :NEW.TAX_PENSION := :NEW.GROSS_TOTAL * (TAX_PENSION_PERCENTAGE / 100);
    :NEW.TAX_HEALTH := :NEW.GROSS_TOTAL * (TAX_HEALTH_PERCENTAGE / 100);
    :NEW.GROSS_TAXABLE := :NEW.GROSS_TOTAL - :NEW.TAX_PENSION - :NEW.TAX_HEALTH;
    :NEW.TAX_INCOME := :NEW.GROSS_TAXABLE * (TAX_INCOME_PERCENTAGE / 100);
    :NEW.NET_SALARY := :NEW.GROSS_TOTAL - :NEW.TAX_INCOME - :NEW.TAX_HEALTH - :NEW.TAX_PENSION - :NEW.DEDUCTIONS;
END;

CREATE OR REPLACE TRIGGER COMPUTE_SALARY_CURRENT_EMPLOYEE
BEFORE UPDATE ON EMPLOYEES
FOR EACH ROW
DECLARE
    TAX_PENSION_PERCENTAGE INT;
    TAX_HEALTH_PERCENTAGE INT;
    TAX_INCOME_PERCENTAGE INT;
BEGIN
    SELECT DEFAULT_PERCENTAGE_TAX_PENSION, DEFAULT_PERCENTAGE_TAX_HEALTH, DEFAULT_PERCENTAGE_TAX_INCOME
    INTO TAX_PENSION_PERCENTAGE, TAX_HEALTH_PERCENTAGE, TAX_INCOME_PERCENTAGE
    FROM PERCENTAGES;

    :NEW.GROSS_TOTAL := :NEW.GROSS_SALARY * (1 + :NEW.GROSS_INCREASE / 100) + :NEW.GROSS_PRIZES;
    :NEW.TAX_PENSION := :NEW.GROSS_TOTAL * (TAX_PENSION_PERCENTAGE / 100);
    :NEW.TAX_HEALTH := :NEW.GROSS_TOTAL * (TAX_HEALTH_PERCENTAGE / 100);
    :NEW.GROSS_TAXABLE := :NEW.GROSS_TOTAL - :NEW.TAX_PENSION - :NEW.TAX_HEALTH;
    :NEW.TAX_INCOME := :NEW.GROSS_TAXABLE * (TAX_INCOME_PERCENTAGE / 100);
    :NEW.NET_SALARY := :NEW.GROSS_TOTAL - :NEW.TAX_INCOME - :NEW.TAX_HEALTH - :NEW.TAX_PENSION - :NEW.DEDUCTIONS;
END;

INSERT INTO EMPLOYEES(SURNAME, FIRST_NAME, OCCUPATION, GROSS_SALARY)
VALUES ('Ponta', 'Ciprian', 'Software Engineer', 5000);
INSERT INTO EMPLOYEES(SURNAME, FIRST_NAME, OCCUPATION, GROSS_SALARY)
VALUES ('Popescu', 'Ion', 'Engineer', 4000);
INSERT INTO EMPLOYEES(SURNAME, FIRST_NAME, OCCUPATION, GROSS_SALARY)
VALUES ('Hustea', 'Cristina', 'Software Architect', 8500);

UPDATE EMPLOYEES
SET GROSS_INCREASE = 10
WHERE SURNAME = 'Popescu' and FIRST_NAME = 'Ion';

DELETE FROM EMPLOYEES WHERE SURNAME = 'Hustea' and FIRST_NAME = 'Cristina';

SELECT * FROM EMPLOYEES;
----------------------------------------------------------------------------------------------------------------------